# Generated by Django 4.1.5 on 2023-01-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contend_id',
            new_name='content_id',
        ),
    ]
